---
# This is a role for setting up the server.

- name: Add user and set password
  user:
    name: '{{ username }}'
    password: '{{ password | password_hash(''sha512'') }}'
    shell: '/bin/bash'

- name: Install packages
  apt:
    pkg:
     - telnetd
     - apache2
     - vsftpd
    update_cache: yes

- name: Start vsftpd service
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Start vsftpd service
      systemd:
        name: vsftpd
        state: started

#- name: Change Telnet port
#  replace:
#    path: /etc/services
#    regexp: '23/tcp'
#    replace: '{{ telnet_port }}/tcp'

# xinetd must be installed after changing the Telnet port
#- name: Install xinetd package
#  apt:
#    name: xinetd

- name: Create privilege escalation vulnerability
  lineinfile:
    path: /etc/sudoers
    line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'

#- name: Place flag
#  copy:
#    dest: '/home/{{ username }}/flag.txt'
#    owner: '{{ username }}'
#    content: "{{ flag }}\n"
#    mode: '0600'

#- name: Place second flag
#  copy:
#    dest: '/root/flag.txt'
#    owner: root
#    content: "{{ flag_2 }}\n"
#    mode: '0600'

#####
- name: Start Apache service
  service:
    name: apache2
    state: started

###########################################################

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'
...