---
# This is a role for setting up the server.

- name: Add user and set password
  user:
    name: '{{ username }}'
    password: '{{ password | password_hash(''sha512'') }}'
    shell: '/bin/bash'

- name: Install packages
  apt:
    pkg:
     - telnetd
     - apache2
     - vsftpd
    update_cache: yes

########################################################################################

# start vsftpd service
- name: Start vsftpd service
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Start vsftpd service
      systemd:
        name: vsftpd
        state: started

# enable vsftp service
- name: Enable vsftpd service
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Enable vsftpd service
      systemd:
        name: vsftpd
        enabled: yes

# add ftp user
- name: Add testuser
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Add testuser
      user:
        name: testuser
        state: present
        createhome: yes
  
# add password
- name: Set password for testuser
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Set password for testuser
      user:
        name: testuser
        password: "3c68d56e84db9a87f3b165b05dc8cd2f7df60e32f12d9508280511609980cf3dd6355b65017dc09fa46d4aa51fd140f3e00ec9644dd443defcd2ddfba8fbd13a"  # Replace with the actual encrypted password

    - name: Change password interactively
      shell: "echo 'new_password' | passwd --stdin testuser"
      vars:
        ansible_ssh_pass: ""  # Replace with your sudo password


- name: Allow port 20/tcp with ufw
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Allow port 20/tcp
      ufw:
        rule: allow
        port: 20/tcp

- name: Allow port 21/tcp with ufw
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Allow port 21/tcp
      ufw:
        rule: allow
        port: 21/tcp

# Change default directory
- name: Create directory /srv/ftp/djtmecuocdoi
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Create directory
      file:
        path: /srv/ftp/djtmecuocdoi
        state: directory

- name: Modify home directory for ftp user
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Modify home directory
      user:
        name: ftp
        home: /srv/ftp/djtmecuocdoi

# Restart ftp service
- name: Restart vsftpd service
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Restart vsftpd service
      systemd:
        name: vsftpd
        state: restarted

# Create vsftpd.conf file
- name: Create vsftpd.conf file
  copy:
    dest: /etc/vsftpd.conf
    src: vsftpd.conf
    force: true

# Create userlist file
- name: Create userlist file
  copy:
    dest: /etc/vsftpd/user_list
    src: userlist
    force: true

# Create user_config_dir directory
- name: Create directory /etc/vsftpd/user_config_dir
  hosts: 192.168.20.5
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Create directory
      file:
        path: /etc/vsftpd/user_config_dir
        state: directory

# Create testuser file
- name: Create testuser file
  copy:
    dest: /etc/vsftpd/user_config_dir/testuser
    src: testuser
    force: true

# Restart FTP
- name: Restart vsftpd service
  hosts: your_target_hosts
  become: true  # To execute commands as sudo
  
  tasks:
    - name: Restart vsftpd service
      systemd:
        name: vsftpd
        state: restarted

########################################################################################

#- name: Change Telnet port
#  replace:
#    path: /etc/services
#    regexp: '23/tcp'
#    replace: '{{ telnet_port }}/tcp'

# xinetd must be installed after changing the Telnet port
#- name: Install xinetd package
#  apt:
#    name: xinetd

- name: Create privilege escalation vulnerability
  lineinfile:
    path: /etc/sudoers
    line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'

#- name: Place flag
#  copy:
#    dest: '/home/{{ username }}/flag.txt'
#    owner: '{{ username }}'
#    content: "{{ flag }}\n"
#    mode: '0600'

#- name: Place second flag
#  copy:
#    dest: '/root/flag.txt'
#    owner: root
#    content: "{{ flag_2 }}\n"
#    mode: '0600'

#####
- name: Start Apache service
  service:
    name: apache2
    state: started

###########################################################

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'
...
